spring:
  boot:
    admin:
      client:
        url: http://localhost:9090/
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:9761}/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'